update rcfiles

diff --git a/dot-files/zshrc b/dot-files/zshrc
--- a/dot-files/zshrc
+++ b/dot-files/zshrc
@@ -34,8 +34,7 @@ else
 fi
 
 PROMPT2="%_%% "
-
-SPROMPT="%r? べ, 別にあんたのために修正したんじゃないんだからね! [n,y,a,e]:"
+SPROMPT="%r? べ, 別にあんたのために修正したんじゃないからね! [n,y,a,e]:"
 
 HISTFILE=~/.zsh_history
 HISTSIZE=10000
@@ -44,47 +43,94 @@ setopt hist_ignore_dups     # ignore duplication command history list
 setopt share_history        # share command history data
 bindkey -e
 
-OS=`uname`
-
-export DISPLAY=:0.0
-export MAKE_MODE=unix
-
-export PATH=./:/bin:/usr/bin:/usr/local/bin:/sbin
-export LD_LIBRARY_PATH=/lib:/usr/bin:/usr/local/lib:/usr/local/jsk/lib
-export PATH=$PATH:/usr/lib/lapack
-
-#export LANG=C
-
-#for GAUCHE
-#SLIB
-export SCHEME_LIBRARY_PATH="/usr/local/lib/slib/"
-#LOAD PATH
-export GAUCHE_LOAD_PATH=$GAUCHE_LOAD_PATH:$HOME/prog:$HOME/prog/grgr/work/garaemon
-
 #alias
-#alias ls='\ls -CF --color=auto --show-control-chars'
-alias ls='\ls -GF'
+alias ls='\ls -GF --color=auto'
 alias cp='cp -v'
 alias mv='mv -v'
 alias grep='grep --color=auto'
 
 #ssh-agent
-echo -n "ssh-agent: "
-source ~/.ssh-agent-info
-ssh-add -l >&/dev/null
-if [ $? = 2 ] ; then
-    echo -n "ssh-agent: restart...."
-    ssh-agent >~/.ssh-agent-info
-    source ~/.ssh-agent-info
-fi
-if ssh-add -l >&/dev/null ; then
-    echo "ssh-agent: Identity is already stored."
-else
+# you always need to cal init_ssh_agent when you want to activate ssh-agent
+init_ssh_agent () {
+    eval `ssh-agent`
+    mkdir -p $HOME/.tmp/ssh-agent/
     ssh-add
+    if [ $? = "0" ]; then
+        local agent="$HOME/.tmp/ssh-agent/`hostname`_local"
+        ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
+    else
+        echo "init failed"
+        return 1
+    fi
+}
+
+update_ssh_agent () {
+    update_ssh_agent_ "$HOME/.tmp/ssh-agent/`hostname`_local" \
+        || update_ssh_agent_ "$HOME/.tmp/ssh-agent/`hostname`"
+}
+
+update_ssh_agent_ () {
+    local agent="$1"
+    if [ -z "$agent" ]; then
+        return 1
+    fi
+
+    if [ -S "$agent" ]; then
+        if [ ! "$SSH_AUTH_SOCK" -ef "$agent" ]; then
+            export SSH_AUTH_SOCK_OLD=$SSH_AUTH_SOCK
+        fi
+
+        export SSH_AUTH_SOCK=$agent
+        return 0
+    elif [ ! -S "$SSH_AUTH_SOCK" ]; then
+        echo "no ssh-agent"
+        if [ -L "$agent" ]; then
+            rm -rf $agent
+        fi
+        if [ -n "$SSH_AUTH_SOCK_OLD" ]; then
+            if [ -S "$SSH_AUTH_SOCK_OLD" ]; then
+                SSH_AUTH_SOCK=$SSH_AUTH_SOCK_OLD
+            fi
+            unset SSH_AUTH_SOCK_OLD
+            update_ssh_agent
+        fi
+    elif [ ! -L "$SSH_AUTH_SOCK" ]; then
+        ssh-add -l >/dev/null \
+            && ln -snf "$SSH_AUTH_SOCK" $agent && export SSH_AUTH_SOCK=$agent
+    fi
+}
+
+# X Window Setup
+function get_xserver ()
+{
+    case $TERM in
+        xterm )
+            XSERVER=$(who am i | awk '{print $NF}' | tr -d ')''(' ) 
+            XSERVER=${XSERVER%%:*}
+            ;;
+        aterm | rxvt)
+        # find some code that works here.....
+            ;;
+    esac  
+}
+
+if [ -z ${DISPLAY:=""} ]; then
+    get_xserver
+    if [[ -z ${XSERVER}  || ${XSERVER} == $(hostname) || ${XSERVER} == "unix" ]]; then 
+        DISPLAY=":0.0"          # Display on local host
+    else                
+        DISPLAY=${XSERVER}:0.0  # Display on remote host
+    fi
 fi
 
-# load each architecture settings ...
-#cygwin load
+export DISPLAY
+
+if [ -e $HOME/.zshrc.jsk ]; then
+    echo loading jsk setup file ...
+    source $HOME/.zshrc.jsk
+fi
+
+OS=`uname`
 if [ "$OS" = "CYGWIN_NT-5.1" -o "$OS" = "CYGWIN_NT-6.0" ] ; then
     if [ -e $HOME/.zshrc.cygwin ]; then
         echo loading cygwin setup file ...
@@ -105,35 +151,16 @@ elif [ "$OS" = "Darwin" ] ; then
         source $HOME/.zshrc.darwin
     fi
 fi
-echo loading jsk setup file ...
-source $HOME/.zshrc.jsk
 
-# screen
-alias scrr='screen -U -D -RR'
-alias s='screen -U'
-
-#fortune
-if [ "$OS" = "CYGWIN_NT-5.1" -o "$OS" = "CYGWIN_NT-6.0" ] ; then
-    echo -e "\n"
-    #fortune
-    echo -e "\n"
-fi
-alias slime="emacs -f slime"
-
-export PATH=$PATH:$HOME/prog/acl
-
-export PATH=$PATH:$HOME/prog/util
-
-export PATH=$PATH:$HOME/gprog/emacs-settings
-source ~/.zshrc.ros
-export PATH=$PATH:$HOME/gprog
-
-#export CLASSPATH=$CLASSPATH:$HOME/gprog/ditaa/trunk
-if [ `which trash-put` ]; then 
-    alias rm='trash-put -v'
+# ros zshrc
+if [ -e $HOME/.zshrc.cturtle.ros ]; then
+    source $HOME/.zshrc.cturtle.ros
 fi
 
-export PATH=$PATH:$HOME/gprog/glc/bin
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/gprog/glc/lib
-export PATH=$HOME/gprog/depot_tools:"$PATH"
-export PATH=$HOME/gprog/platex-create-pkg:"$PATH"
+# customizing zshrc?
+if [ -e $HOME/.zshrc.mine ]; then
+    source $HOME/.zshrc.mine
+fi
+
+
+alias rm='trash-put -v'
